In [1]:
# import libraries
import numpy as np
import torch

## Using numpy

In [14]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round(np.matmul(A, B),2)), print(' ')
print(np.round(A@B, 2)), print(' ')
# print(np.round(A@C, 2)), print(' ')
# print(np.round(B@A, 2)), print(' ')
print(np.round(C.T@A, 2))

[[ 0.99 -0.34 -0.01  0.61  0.35]
 [ 3.11 -1.41 -1.29  1.8  -1.35]
 [ 0.51  1.02  1.49 -0.57  2.42]]
 
[[ 0.99 -0.34 -0.01  0.61  0.35]
 [ 3.11 -1.41 -1.29  1.8  -1.35]
 [ 0.51  1.02  1.49 -0.57  2.42]]
 
[[ 0.65 -2.3   0.34  1.31]
 [ 0.13 -0.53  0.01  0.25]
 [-1.22  1.43 -0.4  -1.82]
 [-0.54  1.33  0.42 -0.7 ]
 [-0.66  0.89 -0.66 -1.18]
 [-2.01  3.82  0.12 -2.96]
 [-0.1  -0.14 -0.39 -0.24]]


## Using pytorch

In [17]:
# Create some random matrices
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor(C1, dtype=torch.float) # convert C1 to pytorch tensor

# try some multiplications....
# print(np.round(A@B, 2)), print(' ')
# print(np.round(A@B.T, 2)), print(' ')
print(np.round( A@C1, 2)), print(' ')
print(np.round( A@C2, 2))

tensor([[ 1.4900,  1.3400,  0.6900,  0.2200, -0.4000, -1.5600, -0.0100],
        [-2.3500, -0.9200,  0.3800,  1.3400, -1.0200, -1.3500,  3.3100],
        [-2.0300,  0.7600, -0.8300, -1.2100,  1.2500,  0.2400, -1.7800]],
       dtype=torch.float64)
 
tensor([[ 1.4900,  1.3400,  0.6900,  0.2200, -0.4000, -1.5600, -0.0100],
        [-2.3500, -0.9200,  0.3800,  1.3400, -1.0200, -1.3500,  3.3100],
        [-2.0300,  0.7600, -0.8300, -1.2100,  1.2500,  0.2400, -1.7800]])


<ipython-input-17-5eaf8a9c6df4>:10: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(np.round( A@C1, 2)), print(' ')
