In [1]:
# import libraries
import torch
import torch.nn as nn
import torch.nn.functional as F

## Using dropout

In [69]:
# define a dropout instance and make some data
prob = .5

dropout = nn.Dropout(p=prob)
x = torch.ones(10)

# let's see what dropout returns
y = dropout(x) # non-zero values are scale up
print(x)
print(y)
print(y*(1-prob))
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 2., 2., 0., 2., 2., 2., 2., 2., 2.])
tensor([0., 1., 1., 0., 1., 1., 1., 1., 1., 1.])
tensor(1.6000)


In [54]:
# dropout is turned off when evaluating the model
dropout.eval()
y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [56]:
# annoyingly, F.dropout() is not deactivated in eval mode:
dropout.eval()
y = F.dropout(x)
print(y)
print(torch.mean(y))

tensor([2., 0., 0., 0., 2., 2., 2., 2., 2., 2.])
tensor(1.4000)


In [59]:
# but you can manually switch it off
# dropout.eval()
y = F.dropout(x,training=False)

print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [68]:
# the model needs to be reset after toggling into eval mode
dropout.train()
y = dropout(x)
print(y) # with dropout

dropout.eval()
y = dropout(x)
print(y) # without dropout

# dropout.train()
y = dropout(x)
print(y) # still w/o dropout ;)

dropout.train()
y = dropout(x)
print(y) # still w/o dropout ;)

tensor([0., 2., 0., 2., 0., 0., 2., 0., 0., 2.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([2., 0., 2., 0., 0., 2., 0., 0., 2., 0.])
