In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [2]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )

deepnet = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [3]:
widenet

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)

## Peeking inside the network

In [13]:
# check out the parameters
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[ 0.0574, -0.0095],
        [-0.0127, -0.6227]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.1509,  0.4511], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.0888,  0.3321],
        [-0.6020, -0.2909]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.4418,  0.2142], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[ 0.3140, -0.2682],
        [-0.2180, -0.6586],
        [ 0.4578,  0.1905]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.4277,  0.2184,  0.0391], requires_grad=True))
 


In [5]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():
  if 'bias' in p[0]:
    numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
  if 'bias' in paramName:
    numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [6]:
# just the parameters
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[-0.5484, -0.0437],
        [ 0.1025,  0.2314],
        [ 0.1780, -0.0782],
        [ 0.1030, -0.3185]], requires_grad=True)
 
Parameter containing:
tensor([ 0.3590, -0.3767, -0.3813, -0.1572], requires_grad=True)
 
Parameter containing:
tensor([[ 0.3901,  0.3908,  0.1513,  0.1815],
        [ 0.2619,  0.1064, -0.0829, -0.3824],
        [ 0.2812,  0.3141, -0.0186,  0.1706]], requires_grad=True)
 
Parameter containing:
tensor([-0.3676,  0.3150,  0.2750], requires_grad=True)
 


In [7]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [8]:
# btw, can also use list comprehension

nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet has %s parameters'%nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [9]:
# A nice simple way to print out the model info.
from torchsummary import summary
summary(widenet,(1,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
